eww open blur
eww open lock
eww open github
eww open terminal
eww open instagram
eww open reddit
eww open facebook
eww open code
eww open file
eww open music
eww open date
eww open clock
eww open vol
eww open bright
eww open file
